ELASTICSEARCH_SERVER: "10.2.0.7"
SITEMAPS_FILE: "sitemaps.csv"
HBASE_TIMEOUT: 30000
HBASE_THRIFT_HOST: "10.2.0.17"
HBASE_THRIFT_PORT: "9090"
LOCATIONS_FILE: "/home/cia/bitbucket/frontera/examples/cluster/bc/config/locations.pkl"
LANGUAGES_FILE: "/home/cia/bitbucket/frontera/examples/cluster/bc/config/languages.pkl"
CACHE_LOCATION: "/home/cia/bitbucket/frontera/examples/sitemap_processor/"
