ELASTICSEARCH_SERVER: 
- "10.2.0.7"
- "10.2.0.25"
- "10.2.0.24"
FEED_FILE: "feeds.list"
HBASE_TIMEOUT: 30000
HBASE_THRIFT_HOST: "10.2.0.17"
HBASE_THRIFT_PORT: "9090"
LOCATIONS_FILE: "/home/cia/bitbucket/frontera/examples/cluster/bc/config/locations.pkl"
LANGUAGES_FILE: "/home/cia/bitbucket/frontera/examples/cluster/bc/config/languages.pkl"
CACHE_LOCATION: "/home/cia/bitbucket/frontera/examples/feed_parser/"
